networks:
    gptnetwork:
        external: true
        name: work_gptnetwork
services:
    api4sensevoice-meetnotesai:
        container_name: api4sensevoice-meetnotesai
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        environment:
            - PORT=27000
            - SSL_CERT_FILE=/workspace/ssl/holardata.com.pem
            - SSL_KEY_FILE=/workspace/ssl/holardata.com.key
            - SV_THR=0.3
            - CHUNK_SIZE_MS=300
            - SAMPLE_RATE=16000
            - AVG_LOGPROB_THR=-0.25
        healthcheck:
            interval: 2m
            retries: 3
            start_period: 60s
            test:
                - CMD
                - sh
                - -c
                - curl -f -k https://localhost:27000/client_wss.html || curl -f http://localhost:27000/client_wss.html
            timeout: 10s
        image: docker.holardata.com:5100/box/api4sensevoice:v2.0-arm64-cpu
        networks:
            - gptnetwork
        restart: "no"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - /root/meetnotesai/upload/speaker:/app/speaker:ro
            - /root/reminderv2/models:/workspace/models
            - /etc/nginx/conf.d:/workspace/ssl:ro
    holarllm-meetnotesai:
        container_name: holarllm-meetnotesai
        environment:
            - SERVER_PORT=9122
            - MYSQL_HOST=host.docker.internal
            - MYSQL_PORT=3306
            - MYSQL_DB=holarllm_meetnotesai
            - MYSQL_USER=root
            - MYSQL_PASSWORD=Collect%2017
        extra_hosts:
            - host.docker.internal:host-gateway
        image: docker.holardata.com:5100/box/holarllm:v1.0
        networks:
            - gptnetwork
        privileged: true
        restart: "no"
    holarmeetnotesai:
        container_name: holarmeetnotesai
        extra_hosts:
            - host.docker.internal:host-gateway
        image: docker.holardata.com:5100/box/meetnotesai:v1.2.2
        networks:
            - gptnetwork
        privileged: true
        restart: "no"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - /etc/nginx/conf.d/holardata.com.pem:/etc/nginx/conf.d/holardata.com.pem:ro
            - /etc/nginx/conf.d/holardata.com.key:/etc/nginx/conf.d/holardata.com.key:ro
            - /root/meetnotesai/log/:/data/meetnotesai/log/
            - /root/meetnotesai/upload/:/data/meetnotesai/upload/
            - /root/box_manager/asr_param/hotwords.txt:/data/meetnotesai/asr_param/hotwords.txt:ro
            - /root/box_manager/asr_param/asr_param.json:/data/meetnotesai/asr_param/asr_param.json:ro
    holarmeetnotesai-front:
        container_name: holarmeetnotesai-front
        extra_hosts:
            - host.docker.internal:host-gateway
        image: docker.holardata.com:5100/box/meetnotesai-front:v1.2.2
        networks:
            - gptnetwork
        ports:
            - ${PANEL_APP_PORT_HTTPS}:9102
        privileged: true
        restart: "no"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - /etc/nginx/conf.d/holardata.com.pem:/etc/nginx/conf.d/holardata.com.pem:ro
            - /etc/nginx/conf.d/holardata.com.key:/etc/nginx/conf.d/holardata.com.key:ro
version: "3.3"
