networks:
    gptnetwork:
        external: true
        name: work_gptnetwork
services:
    holar2dhuman:
        container_name: holarmetaman2d
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        extra_hosts:
            - host.docker.internal:host-gateway
        image: docker.holardata.com:5100/box/2dhuman:v2.1.30
        labels:
            createdBy: Apps
        networks:
            - gptnetwork
        ports:
            - ${HOST_IP}:${PANEL_APP_PORT_HTTPS}:8700
        privileged: true
        restart: "no"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - /root/2d_humanV2/upload:/root/2d_human/upload
version: "3.3"
