version: '3.3'
services:
  pg:
    image: 064c0b44be20
    container_name: pg
    restart: always
    ports:
      - 5432:5432
    networks:
      - gptnetwork
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./pg/data:/var/lib/postgresql/data
  mongo:
    image: 89b2d35bf1bb
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - gptnetwork
    command: mongod --keyFile /data/mongodb.key --replSet rs0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myusername
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - ./mongo/data:/data/db
      - /tmp:/tmp
    entrypoint:
      - bash
      - -c
      - |
        openssl rand -base64 128 > /data/mongodb.key
        chmod 400 /data/mongodb.key
        chown 999:999 /data/mongodb.key
        echo 'const isInited = rs.status().ok === 1
        if(!isInited){
          rs.initiate({
              _id: "rs0",
              members: [
                  { _id: 0, host: "mongo:27017" }
              ]
          })
        }' > /data/initReplicaSet.js
        exec docker-entrypoint.sh "$$@" &
        until mongo -u myusername -p mypassword --authenticationDatabase admin --eval "print('waited for connection')" > /dev/null 2>&1; do
          echo "Waiting for MongoDB to start..."
          sleep 2
        done

        mongo -u myusername -p mypassword --authenticationDatabase admin /data/initReplicaSet.js

        wait $$!
  
  
  mysql:
    image: b1a5ea9fcc4f
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Collect%2017
      - TZ=Asia/Shanghai
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
      --tls_version="TLSv1.2,TLSv1.3"
      --disable-log-bin
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
      - /tmp:/tmp
    networks:
      - gptnetwork
    restart: always

  minio:
    image: 6f3775e162b0
    container_name: minio
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=rag_flow
      - MINIO_ROOT_PASSWORD=infini_rag_flow
      - TZ=Asia/Shanghai
    volumes:
      - ./minio_data:/data
    networks:
      - gptnetwork
    restart: always


networks:
  gptnetwork:


