version: '3.3'
services:
  deepdoc:
    container_name: deepdoc
    image: deepdoc:v6
    #ports:
    #  - 2227:22
    volumes:
      - ./ragflow/root/start.sh:/root/start.sh
      - ./ragflow:/data/work/ragflow
    networks:
      - gptnetwork
    restart: always

networks:
  gptnetwork:

