services:  
  assistant:
    image: assistant:2.0.1
    container_name: ai_assistant
    restart: unless-stopped
    ports:
      - "8366:8366"
    env_file: .env
    command: tail -f /dev/null
    #volumes:
    #  - /data/omniknow2/backend/omniknow2/assistant:/app

networks:
  backend:
    driver: bridge
