networks:
    gptnetwork:
        external: true
        name: work_gptnetwork
services:
    holarchat:
        container_name: holarchat
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        extra_hosts:
            - host.docker.internal:host-gateway
        image: docker.holardata.com:5100/box/chat:v1.3
        networks:
            - gptnetwork
        ports:
            - ${HOST_IP}:${PANEL_APP_PORT_HTTPS}:3001
            - ${HOST_IP}:13002:13002
        privileged: true
        pull_policy: if_not_present
        restart: always
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - /data/holarchat/conf.d/a.conf:/etc/nginx/conf.d/a.conf:ro
            - /etc/nginx/conf.d/holardata.com.pem:/etc/nginx/conf.d/holardata.com.pem:ro
            - /etc/nginx/conf.d/holardata.com.key:/etc/nginx/conf.d/holardata.com.key:ro
            - /data/holarchat/site_config:/data/holarchat/projects/app/public/imgs/pro/site_config
version: "3.3"
