version: '3.7'

services:
  server-api:
    image: aiserver-2.0.0.1:latest
    container_name: ai_server
    restart: always
    networks:
      - cc-net
    ports:
      - "8375:8375"
    env_file: /ManualAI/OmniKnow/omniknow2/server/.env
    command:
      - /bin/bash
      - /aiserverspace/bash/start_main.sh
    volumes:
      - /ManualAI/OmniKnow/omniknow2/server:/aiserverspace

  celery-worker:
    image: aiserver-2.0.0.1:latest
    container_name: ai_server_celery_worker
    restart: always
    networks:
      - cc-net
    command:
      - /bin/bash
      - /aiserverspace/bash/start_celery_worker.sh
    env_file: /ManualAI/OmniKnow/omniknow2/server/.env
    volumes:
      - /ManualAI/OmniKnow/omniknow2/server:/aiserverspace

  celery-beat:
    image: aiserver-2.0.0.1:latest
    container_name: ai_server_celery_beat
    restart: always
    networks:
      - cc-net
    command:
      - /bin/bash
      - /aiserverspace/bash/start_celery_beat.sh
    env_file: /ManualAI/OmniKnow/omniknow2/server/.env
    volumes:
      - /ManualAI/OmniKnow/omniknow2/server:/aiserverspace


networks:
  cc-net:
    external: true
