global:
  imageRegistry: docker.io
  imagePullSecrets: []
  tolerations: []
  nodeSelector: {}
  cattle:
    systemDefaultRegistry: ''
    windowsCluster:
      enabled: false
      tolerations:
      - key: cattle.io/os
        value: linux
        effect: NoSchedule
        operator: Equal
      nodeSelector:
        kubernetes.io/os: linux
      defaultSetting:
        taintToleration: cattle.io/os=linux:NoSchedule
        systemManagedComponentsNodeSelector: kubernetes.io/os:linux
networkPolicies:
  enabled: false
  type: k3s
image:
  longhorn:
    engine:
      registry: ''
      repository: harbor.wuxing.local/longhorn/longhorn-engine
      tag: v1.10.2
    manager:
      registry: ''
      repository: harbor.wuxing.local/longhorn/longhorn-manager
      tag: v1.10.2
    ui:
      registry: ''
      repository: harbor.wuxing.local/longhorn/longhorn-ui
      tag: v1.10.2
    instanceManager:
      registry: ''
      repository: harbor.wuxing.local/longhorn/longhorn-instance-manager
      tag: v1.10.2
    shareManager:
      registry: ''
      repository: harbor.wuxing.local/longhorn/longhorn-share-manager
      tag: v1.10.2
    backingImageManager:
      registry: ''
      repository: harbor.wuxing.local/longhorn/backing-image-manager
      tag: v1.10.2
    supportBundleKit:
      registry: ''
      repository: harbor.wuxing.local/longhorn/support-bundle-kit
      tag: v0.0.79
  csi:
    attacher:
      registry: ''
      repository: harbor.wuxing.local/longhorn/csi-attacher
      tag: v4.10.0-20251226
    provisioner:
      registry: ''
      repository: harbor.wuxing.local/longhorn/csi-provisioner
      tag: v5.3.0-20251226
    nodeDriverRegistrar:
      registry: ''
      repository: harbor.wuxing.local/longhorn/csi-node-driver-registrar
      tag: v2.15.0-20251226
    resizer:
      registry: ''
      repository: harbor.wuxing.local/longhorn/csi-resizer
      tag: v1.14.0-20260119
    snapshotter:
      registry: ''
      repository: harbor.wuxing.local/longhorn/csi-snapshotter
      tag: v8.4.0-20251226
    livenessProbe:
      registry: ''
      repository: harbor.wuxing.local/longhorn/livenessprobe
      tag: v2.17.0-20251226
  openshift:
    oauthProxy:
      registry: ''
      repository: ''
      tag: ''
  pullPolicy: IfNotPresent
service:
  ui:
    type: ClusterIP
    nodePort: null
    annotations: {}
  manager:
    type: ClusterIP
    nodePort: ''
persistence:
  defaultClass: true
  defaultFsType: ext4
  defaultMkfsParams: ''
  defaultClassReplicaCount: 3
  defaultDataLocality: disabled
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  migratable: false
  disableRevisionCounter: 'true'
  nfsOptions: ''
  recurringJobSelector:
    enable: false
    jobList: []
  backingImage:
    enable: false
    name: null
    dataSourceType: null
    dataSourceParameters: null
    expectedChecksum: null
  defaultDiskSelector:
    enable: false
    selector: ''
  defaultNodeSelector:
    enable: false
    selector: ''
  unmapMarkSnapChainRemoved: ignored
  dataEngine: v1
  backupTargetName: default
preUpgradeChecker:
  jobEnabled: true
  upgradeVersionCheck: true
csi:
  kubeletRootDir: null
  attacherReplicaCount: null
  provisionerReplicaCount: null
  resizerReplicaCount: null
  snapshotterReplicaCount: null
defaultSettings:
  allowRecurringJobWhileVolumeDetached: null
  createDefaultDiskLabeledNodes: null
  defaultDataPath: null
  defaultDataLocality: null
  replicaSoftAntiAffinity: null
  replicaAutoBalance: null
  storageOverProvisioningPercentage: null
  storageMinimalAvailablePercentage: null
  storageReservedPercentageForDefaultDisk: null
  upgradeChecker: null
  upgradeResponderURL: null
  defaultReplicaCount: null
  defaultLonghornStaticStorageClass: null
  failedBackupTTL: null
  backupExecutionTimeout: null
  restoreVolumeRecurringJobs: null
  recurringSuccessfulJobsHistoryLimit: null
  recurringFailedJobsHistoryLimit: null
  recurringJobMaxRetention: null
  supportBundleFailedHistoryLimit: null
  taintToleration: null
  systemManagedComponentsNodeSelector: null
  priorityClass: longhorn-critical
  autoSalvage: null
  autoDeletePodWhenVolumeDetachedUnexpectedly: null
  blacklistForAutoDeletePodWhenVolumeDetachedUnexpectedly: null
  disableSchedulingOnCordonedNode: null
  replicaZoneSoftAntiAffinity: null
  replicaDiskSoftAntiAffinity: null
  nodeDownPodDeletionPolicy: null
  nodeDrainPolicy: null
  detachManuallyAttachedVolumesWhenCordoned: null
  replicaReplenishmentWaitInterval: null
  concurrentReplicaRebuildPerNodeLimit: null
  concurrentVolumeBackupRestorePerNodeLimit: null
  disableRevisionCounter: '{"v1":"true"}'
  systemManagedPodsImagePullPolicy: null
  allowVolumeCreationWithDegradedAvailability: null
  autoCleanupSystemGeneratedSnapshot: null
  autoCleanupRecurringJobBackupSnapshot: null
  concurrentAutomaticEngineUpgradePerNodeLimit: null
  backingImageCleanupWaitInterval: null
  backingImageRecoveryWaitInterval: null
  guaranteedInstanceManagerCPU: null
  kubernetesClusterAutoscalerEnabled: null
  orphanResourceAutoDeletion: null
  orphanResourceAutoDeletionGracePeriod: null
  storageNetwork: null
  deletingConfirmationFlag: null
  engineReplicaTimeout: null
  snapshotDataIntegrity: null
  snapshotDataIntegrityImmediateCheckAfterSnapshotCreation: null
  snapshotDataIntegrityCronjob: null
  removeSnapshotsDuringFilesystemTrim: null
  fastReplicaRebuildEnabled: null
  replicaFileSyncHttpClientTimeout: null
  longGRPCTimeOut: null
  logLevel: null
  logPath: null
  backupCompressionMethod: null
  backupConcurrentLimit: null
  defaultBackupBlockSize: null
  restoreConcurrentLimit: null
  v1DataEngine: null
  v2DataEngine: null
  dataEngineHugepageEnabled: null
  dataEngineMemorySize: null
  dataEngineCPUMask: null
  replicaRebuildingBandwidthLimit: null
  instanceManagerPodLivenessProbeTimeout: null
  allowEmptyNodeSelectorVolume: null
  allowEmptyDiskSelectorVolume: null
  allowCollectingLonghornUsageMetrics: null
  disableSnapshotPurge: null
  snapshotMaxCount: null
  dataEngineLogLevel: null
  dataEngineLogFlags: null
  freezeFilesystemForSnapshot: null
  autoCleanupSnapshotWhenDeleteBackup: null
  autoCleanupSnapshotAfterOnDemandBackupCompleted: null
  rwxVolumeFastFailover: null
  offlineReplicaRebuilding: null
defaultBackupStore:
  backupTarget: null
  backupTargetCredentialSecret: null
  pollInterval: null
privateRegistry:
  createSecret: null
  registryUrl: null
  registryUser: null
  registryPasswd: null
  registrySecret: null
longhornManager:
  log:
    format: plain
  priorityClass: longhorn-critical
  tolerations: []
  nodeSelector: {}
  serviceAnnotations: {}
longhornDriver:
  log:
    format: plain
  priorityClass: longhorn-critical
  tolerations: []
  nodeSelector: {}
longhornUI:
  replicas: 2
  priorityClass: longhorn-critical
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - longhorn-ui
          topologyKey: kubernetes.io/hostname
  tolerations: []
  nodeSelector: {}
ingress:
  enabled: false
  ingressClassName: null
  host: sslip.io
  tls: false
  secureBackends: false
  tlsSecret: longhorn.local-tls
  path: /
  pathType: ImplementationSpecific
  annotations: null
  secrets: null
enablePSP: false
namespaceOverride: ''
annotations: {}
serviceAccount:
  annotations: {}
metrics:
  serviceMonitor:
    enabled: false
    additionalLabels: {}
    annotations: {}
    interval: ''
    scrapeTimeout: ''
    relabelings: []
    metricRelabelings: []
openshift:
  enabled: false
  ui:
    route: longhorn-ui
    port: 443
    proxy: 8443
enableGoCoverDir: false
extraObjects: []
