networks:
    holardataq-network: null
services:
    holardataq:
        container_name: holardataq
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        environment:
            BACKEND_CORS_ORIGINS: http://localhost,http://localhost:5173,https://localhost,https://localhost:5173
            DEFAULT_PWD: holardata2025
            LOG_LEVEL: INFO
            POSTGRES_DB: holardataq
            POSTGRES_PASSWORD: Password123@pg
            POSTGRES_PORT: 5432
            POSTGRES_SERVER: localhost
            POSTGRES_USER: root
            PROJECT_NAME: holardataq
            SECRET_KEY: y5txe1mRmS_JpOrUzFzHEu-kIQn3lf7ll0AOv9DQh0s
            SERVER_IMAGE_HOST: http://YOUR_SERVE_IP:MCP_PORT/images/
            SQL_DEBUG: false
        extra_hosts:
            - host.docker.internal:host-gateway
        image: docker.holardata.com:5100/box/holardataq:v1.8.0
        networks:
            - holardataq-network
        ports:
            - ${HOST_IP}:${PANEL_APP_PORT_HTTP}:8000
            - ${HOST_IP}:18001:8001
            - ${HOST_IP}:54323:5432
        privileged: true
        restart: "no"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - /opt/holardataq/config:/opt/holardataq/data/config
            - /opt/holardataq/excel:/opt/sqlbot/data/excel
            - /opt/holardataq/file:/opt/sqlbot/data/file
            - /opt/holardataq/images:/opt/sqlbot/images
            - /opt/holardataq/logs:/opt/sqlbot/app/logs
            - /opt/postgresql:/var/lib/postgresql/data
