version: '3.8'

services:
  llm:
    image: asr_offline:1.3.0
    container_name: asr_offline
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    ipc: host
    ports:
      - "5000:5000"
    volumes:
      - /root/.cache/modelscope/:/root/.cache/modelscope/
      - /root/reminderv2/:/root/reminderv2/
      - /root/box_manager/asr_param/:/root/box_manager/asr_param/
      - /dev/shm:/dev/shm
    shm_size: 20g
    ulimits:
      memlock: -1
    environment:
      - CUDA_VISIBLE_DEVICES=0
    working_dir: /root/reminderv2/bin/
    command: gunicorn -w 2 -t 3600 -b 0.0.0.0:5000 audio_analyse:app
    restart: no
    networks:
      - models_network
networks:
  models_network:
    external: true
    name: models_network

