networks:
    gptnetwork:
        external: true
        name: work_gptnetwork
    internal_redis_network:
        driver: bridge
services:
    holarfileparse:
        command:
            - /bin/bash
            - /root/start.sh
        container_name: holarfileparse
        extra_hosts:
            - host.docker.internal:host-gateway
        image: docker.holardata.com:5100/box/fileparse_th:v2.2.2
        networks:
            - gptnetwork
            - internal_redis_network
        ports:
            - ${PANEL_APP_PORT_HTTP}:5176
            - 5558:5558
        privileged: true
        restart: "no"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - /root/holarfileparse2.0/static:/root/pdf_parse_web/static
            - /root/holarfileparse2.0/assets:/root/pdf_parse_web/com/assets
    holarfileparse-redis:
        command:
            - redis-server
            - --bind 0.0.0.0
            - --port 6379
            - --requirepass fileparse_holar
        container_name: holarfileparse-redis
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        image: docker.holardata.com:5100/box/redis:8.2.1
        networks:
            - internal_redis_network
        restart: "no"
version: "3.3"
