{
 "title": "Tetragon",
 "description": "Get an overview of your Tetragon installation on your cluster.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{job=\"tetragon\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Policies State",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod, state) (\n  tetragon_tracingpolicy_loaded\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Event Reported",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(\n    time() - tetragon_events_last_exported_timestamp\n)",
     "legendFormat": "Last event"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "up{job=\"tetragon\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Policy Kernel Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tetragon_tracingpolicy_kernel_memory_bytes",
     "legendFormat": "{{policy}}"
    }
   ]
  },
  {
   "title": "Missed Probes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(tetragon_missed_prog_probes_total[$__rate_interval]))",
     "legendFormat": "Probes missed by program"
    },
    {
     "expr": "sum(rate(tetragon_missed_link_probes_total[$__rate_interval]))",
     "legendFormat": "Probes missed by link"
    }
   ]
  },
  { "title": "Events activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Events/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(tetragon_events_exported_total[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Events Loss/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(tetragon_observer_ringbuf_events_lost_total[$__rate_interval])\n+\nrate(tetragon_observer_ringbuf_queue_events_lost_total[$__rate_interval])\n+\nrate(tetragon_notify_overflowed_events_total[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Handler Errors/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(tetragon_handler_errors_total[$__rate_interval])\n)",
     "legendFormat": "Handler errors/sec"
    }
   ]
  },
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Events by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum by (type) (\n  rate(tetragon_events_total[$__rate_interval])\n)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Policy Events/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by (policy) (\n  increase(tetragon_policy_events_total[$__rate_interval])\n)",
     "legendFormat": "{{policy}}"
    }
   ]
  },
  { "title": "Top activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Top Workloads by Events",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  sum by (workload) (\n    rate(tetragon_events_total{workload!=\"\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Syscalls",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  sum by (syscall) (\n    rate(tetragon_syscalls_total{syscall!=\"\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Data quality", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Process Cache Misses/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(\n  rate(tetragon_process_cache_misses_total[$__rate_interval])\n)",
     "legendFormat": "Exported"
    }
   ]
  },
  {
   "title": "Event Cache Errors/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(\n  rate(tetragon_event_cache_errors_total[$__rate_interval])\n)",
     "legendFormat": "Exported"
    }
   ]
  },
  {
   "title": "Process Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "tetragon_process_cache_size", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Events Missing Process Info/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(tetragon_events_missing_process_info_total[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"tetragon\"}[$__rate_interval]) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"tetragon\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"tetragon\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"tetragon\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}