networks:
    gptnetwork:
        external: true
        name: work_gptnetwork
services:
    holarkanban:
        container_name: holarkanban
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        extra_hosts:
            - host.docker.internal:host-gateway
        image: docker.holardata.com:5100/box/kanban:v1.0
        networks:
            - gptnetwork
        ports:
            - ${HOST_IP}:${WEB_PORT_HTTP}:19001
        privileged: true
        restart: always
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - /root/lingtu/image:/root/lingtu/image
version: "3.3"
