networks:
    gptnetwork:
        external: true
        name: work_gptnetwork
services:
    backend:
        container_name: gwxz-v2-backend
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=500MB
            - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=500MB
            - HOLAR_LICENSE_REMOTE_URL=http://host.docker.internal:29000
            - HOLAR_LICENSE_PN=holar_gwxz
            - HOLAR_LICENSE_ENFORCE_ON_LOGIN=true
        extra_hosts:
            - host.docker.internal:host-gateway
        image: docker.holardata.com:5100/holawrite/gwxz/backend:v2.2.5
        networks:
            - gptnetwork
        privileged: true
        restart: "no"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - /data/holar_write/gwxz/upload:/data/holar_write/gwxz/upload
    frontend:
        container_name: gwxz-v2-frontend
        depends_on:
            - backend
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        extra_hosts:
            - host.docker.internal:host-gateway
        image: docker.holardata.com:5100/holawrite/gwxz/frontend:v2.2.5
        networks:
            - gptnetwork
        ports:
            - ${HOST_IP}:${PANEL_APP_PORT_HTTPS}:443
        privileged: true
        restart: "no"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - /etc/nginx/conf.d/holardata.com.pem:/etc/nginx/conf.d/holardata.com.pem:ro
            - /etc/nginx/conf.d/holardata.com.key:/etc/nginx/conf.d/holardata.com.key:ro
