version: "3.7"

services:
  assistant:
    image: assistant:latest
    container_name: assistant
    stdin_open: true
    tty: true
    restart: always
    networks:
      - cc-net
    ports:
      - "8366:8366"
    env_file: /ManualAI/OmniKnow/omniknow2/assistant/.env
    volumes:
      - /ManualAI/OmniKnow/omniknow2/:/assistantspace
      - /ManualAI/OmniKnow/omniknow2/assistant/logs:/assistantspace/logs
    command:
      - /bin/bash
      - /assistantspace/assistant/bash/start_assistant.sh


networks:
  cc-net:
    external: true
