services:
  qwen3_next_80b_a3b_instruct_nvfp4:
    image: docker.holardata.com:5100/nvidia/vllm:0.22.1rc1-cuda13.0-tf5-jetson-thor
    container_name: qwen3_next_80b_a3b_instruct_nvfp4
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    ipc: host
    ports:
      - "17104:17104"
    volumes:
      - /root/.cache/modelscope/:/root/.cache/modelscope/
      - /dev/shm:/dev/shm
    shm_size: 60g
    ulimits:
      memlock: -1
    environment:
      - CUDA_VISIBLE_DEVICES=0
    command: >
      --model /root/.cache/modelscope/hub/models/holardata/Qwen3-Next-80B-A3B-Instruct-NVFP4-FP8KV/
      --served-model-name  qwen3_next_80b_a3b_instruct_nvfp4 
      --trust-remote-code  
      --gpu-memory-utilization 0.55 
      --max-num-seqs 64 
      --max-model-len 32000 
      --host 0.0.0.0 
      --port 17104 
      --kv-cache-dtype  fp8_e4m3  
      --tool-call-parser hermes 
      --enable-auto-tool-choice 
      --mamba-cache-dtype float16 
    restart: no
    networks:
      - models_network
networks:
  models_network:
    external: true
    name: models_network
