version: '3.7'

services:
  parser:
    image: parser:latest
    container_name: parser
    runtime: nvidia
    privileged: true
    restart: always
    shm_size: "16g"
    networks:
      - cc-net
    environment:
      CUDA_VISIBLE_DEVICES: "0"
    ports:
      - "8010:8010"
    volumes:
      - /ManualAI/OmniKnow/omniknow2/parser/logs:/parserspace/logs
      - /ManualAI/OmniKnow/omniknow2/parser/rag:/parserspace/rag
      - /ManualAI/OmniKnow/omniknow2/parser/bash:/parserspace/bash
    env_file: /ManualAI/OmniKnow/omniknow2/parser/rag/.env
    command:
      - /bin/bash
      - /parserspace/bash/start_parser.sh


  img_service:
    image: parser:latest
    container_name: img_service
    runtime: nvidia
    privileged: true
    restart: always
    shm_size: "16g"
    networks:
      - cc-net
    environment:
      CUDA_VISIBLE_DEVICES: "0"
    ports:
      - "18080:18080"
    volumes:
      - /ManualAI/OmniKnow/omniknow2/parser/logs:/parserspace/logs
      - /ManualAI/OmniKnow/omniknow2/parser/rag:/parserspace/rag
      - /ManualAI/OmniKnow/omniknow2/parser/bash:/parserspace/bash
      - /ManualAI/OmniKnow/models:/parserspace/models
    env_file: /ManualAI/OmniKnow/omniknow2/parser/rag/.env
    command:
      - /bin/bash
      - /parserspace/bash/start_imgserver.sh


networks:
  cc-net:
    external: true
