version: '3.7'

services:
  qwen-embedding:
    image: ghcr.io/nvidia-ai-iot/vllm:latest-jetson-orin
    container_name: qwen-embedding
    runtime: nvidia
    privileged: true
    restart: always
    shm_size: "16g"
    networks:
      manualai_network:
        ipv4_address: 172.18.0.121
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8021:8021"
    volumes:
      - /ManualAI/.cache:/ManualAI/.cache
      - /ManualAI/models:/ManualAI/models
    command: >
      vllm serve /ManualAI/models/Qwen3-Embedding-0.6B
      --runner pooling
      --dtype auto
      --host 0.0.0.0
      --port 8021
      --hf_overrides '{"matryoshka_dimensions":[1024]}'
      --served-model-name qwen-embedding
      --no-enable-prefix-caching
      --gpu-memory-utilization 0.08
      --tensor-parallel-size 1
      --trust-remote-code
      --max-model-len 32768

  qwen-rerank:
    image: ghcr.io/nvidia-ai-iot/vllm:latest-jetson-orin
    container_name: qwen-rerank
    runtime: nvidia
    privileged: true
    restart: always
    shm_size: "16g"
    networks:
      manualai_network:
        ipv4_address: 172.18.0.122
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8022:8022"
    volumes:
      - /ManualAI/.cache:/ManualAI/.cache
      - /ManualAI/models:/ManualAI/models
    command: >
      vllm serve /ManualAI/models/Qwen3-Reranker-0.6B
      --dtype auto
      --hf_overrides '{"architectures":["Qwen3ForSequenceClassification"],"classifier_from_token":["no","yes"],"is_original_qwen3_reranker":true}'
      --host 0.0.0.0
      --port 8022
      --gpu-memory-utilization 0.1
      --served-model-name qwen-rerank
      --max-model-len 32768
      --trust-remote-code
      --enforce-eager

networks:
  manualai_network:
    external: true
