services:

  mineru-api:
    image: mineru-gpu-dustynv:v2.7.6-arm64-transformers
    runtime: nvidia
    container_name: mineru-api
    restart: always
    profiles: ["api"]
    shm_size: "16g"
    volumes:
      - /ManualAI/Omniknow:/ManualAI/Omniknow
      - /ManualAI/llm/mineru/mineru.json:/root/.mineru/mineru.json:ro
    ports:
      - 8000:8000
    environment:
      - TZ=Asia/Shanghai
      - MINERU_MODEL_SOURCE=local
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - MINERU_LOG_LEVEL=DEBUG
      - VLLM_LOGGING_LEVEL=DEBUG
      - MINERU_HYBRID_BATCH_RATIO=1
      - MINERU_VIRTUAL_VRAM_SIZE=7
    entrypoint: mineru-api
    command:
      --host 0.0.0.0
      --port 8000
      --gpu-memory-utilization 0.4
    ulimits:
      memlock: -1
      stack: 67108864
    ipc: host
    networks:
      manualai_network:
        ipv4_address: 172.18.0.21

networks:
  manualai_network:
    external: true
