version: "3.9"

services:
  assistant:
    image: assistant:3.0.0.0825.39fdf8e
    container_name: assistant
    privileged: true
    stdin_open: true
    tty: true
    networks:
      manualai_network:
        ipv4_address: 172.18.0.130
    ports:
      - "8366:8366"
    volumes:
      - /ManualAI/Omniknow/code/assistant/conf.yaml:/app/conf.yaml
      - /ManualAI/Omniknow/code/assistant/.env:/app/.env
      - ./code/assistant/resources/truck_2190/url.txt:/app/src/subagents/visual3d/resources/truck_2190/url.txt
    environment:
      - TZ=Asia/Shanghai
    restart: always

  server-api:
    image: ai_server:3.1.0.0824.315945
    container_name: ai_server_backend
    privileged: true
    restart: always
    ports:
      - "${ENV_PORT:-8375}:8375"
    env_file: ./code/server/.env
    volumes:
      - ./code/server/.env:/app/.env
      - /ManualAI/Omniknow/code/ai_storage/parser_files:/ManualAI/Omniknow/code/ai_storage/parser_files
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
    networks:
      manualai_network:
        ipv4_address: 172.18.0.131

  celery-worker:
    image: ai_server:3.1.0.0824.315945
    container_name: ai_server_worker
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /ManualAI/Omniknow/code/ai_storage/parser_files:/ManualAI/Omniknow/code/ai_storage/parser_files
    command: >
      celery -A worker_bootstrap:celery_app worker
      --loglevel=info
      -Q celery,document_processing
      -c 3
    env_file: ./code/server/.env
    networks:
      manualai_network:
        ipv4_address: 172.18.0.132
    
  celery-beat:
    image: ai_server:3.1.0.0824.315945
    container_name: ai_server_beater
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    command: >
      celery -A worker_bootstrap:celery_app beat
      --loglevel=info
      -S redbeat.RedBeatScheduler
    env_file: ./code/server/.env
    networks:
      manualai_network:
        ipv4_address: 172.18.0.133

  parser:
    image: parser:2.0.1.058-reportlab
    container_name: parser
    privileged: true
    stdin_open: true
    tty: true
    working_dir: /ManualAI/Omniknow/code/parser/rag
    command: >
      bash -c '
      python api.py 2>&1 | tee -a api.log
      '
    ports:
      - "8008:8008"
    environment:
      TZ: Asia/Shanghai
      HYBRID_TOKENIZER_DIR: ./code/parser/Qwen-tokenizer
    volumes:
      - /ManualAI/Omniknow/code:/ManualAI/Omniknow/code
      - /ManualAI/models:/ManualAI/models
    networks:
      manualai_network:
        ipv4_address: 172.18.0.134
    restart: always


  img_server:
    image: harbor.chicheng.com/omniknow-arm/torch:npu_cunn9_910b_py311
    container_name: img_server
    privileged: true
    working_dir: /ManualAI/Omniknow/code/parser/rag
    command: >
      bash -c 'python3 img_service.py'
    ports:
      - "18080:18080"
    environment:
      TZ: Asia/Shanghai
      CUDA_VISIBLE_DEVICES: 4
      TEI_NPU_DEVICE: 4
      IMG_MODEL_PATH: /ManualAI/models/dinov3-vitl16-pretrain-lvd1689m
    volumes:
      - /ManualAI/Omniknow/code/ai_storage/parser_files:/ManualAI/Omniknow/code/ai_storage/parser_files
      - /usr/local/Ascend/driver:/usr/local/Ascend/driver:ro
      - /usr/local/sbin:/usr/local/sbin:ro
      - /ManualAI/models:/ManualAI/models:rw
      - /dev/davinci_manager:/dev/davinci_manager
      - /dev/hisi_hdc:/dev/hisi_hdc
      - /dev/devmm_svm:/dev/devmm_svm
      - /ManualAI/Omniknow:/ManualAI/Omniknow
    networks:
      manualai_network:
        ipv4_address: 172.18.0.135
    restart: always

    
networks:
  manualai_network:
    external: true
