networks:
    gptnetwork:
        external: true
        name: work_gptnetwork
services:
    holartts:
        container_name: holartts
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        extra_hosts:
            - host.docker.internal:host-gateway
        image: docker.holardata.com:5100/box/tts:v1.0
        networks:
            - gptnetwork
        ports:
            - ${HOST_IP}:8000:8000
        privileged: true
        restart: always
